name: Gradle Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        java: [ '16.0.2' ]
      fail-fast: false
    name: Build - ${{ matrix.os }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Echo JAVA_HOME
        run: echo $JAVA_HOME

      - name: Verify Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Execute jpackage
        run: ./gradlew --info --stacktrace -Pversion="${{ github.ref }}" jpackage

      - name: Upload Mac artifact
        if: matrix.os == 'macOS-latest'
        uses: actions/upload-artifact@v2
        with:
          name: McLauncher-${{ github.ref }}-mac
          path: app/build/jpackage/*.dmg

      - name: Upload Windows artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: McLauncher-${{ github.ref }}-windows
          path: |
            app/build/jpackage/*.msi
            app/build/jpackage/*.exe

      - name: Upload Linux artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: McLauncher-${{ github.ref }}-linux
          path: |
            app/build/jpackage/*.deb
            app/build/jpackage/*.rpm
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        with:
          commitMode: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/download-artifact@v2
        name: Donwload Builds
        with:
          path: artifacts

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            artifacts/McLauncher-${{ github.ref }}-windows/McLauncher SC-${{ github.ref }}.msi
            artifacts/McLauncher-${{ github.ref }}-linux/McLauncher SC-${{ github.ref }}.deb
            artifacts/McLauncher-${{ github.ref }}-mac/McLauncher SC-${{ github.ref }}.dmg
            artifacts/McLauncher-${{ github.ref }}-linux/McLauncher SC-${{ github.ref }}.rpm
            artifacts/McLauncher-${{ github.ref }}-windows/McLauncher SC-${{ github.ref }}.exe

          